# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Aciona o fluxo de trabalho em eventos de solicitação push ou pull, mas apenas para o branch principal
  empurre :
    ramos : [ principal ]
  pull_request :
    ramos : [ principal ]

  # Permite que você execute este fluxo de trabalho manualmente na guia Ações
  workflow_dispatch :

# A execução de um fluxo de trabalho é composta por uma ou mais tarefas que podem ser executadas sequencialmente ou em paralelo
empregos :
  # Este fluxo de trabalho contém um único trabalho chamado "build"
  construir :
    # O tipo de executor em que o trabalho será executado
    roda em : ubuntu-mais recente

    # As etapas representam uma sequência de tarefas que serão executadas como parte do trabalho
    passos :
      # Faz o check-out de seu repositório em $ GITHUB_WORKSPACE, para que seu trabalho possa acessá-lo
      - usa : ações / checkout @ v2

      # Executa um único comando usando o shell runners
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
